{% set name = "dmrseq" %}
{% set version = "1.3.11" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/kdkorthauer/dmrseq.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]

  # these are conda packages that you'll need to install your package
  host:
    - r-base
    - r-nlme
    - r-ggplot2
    - bioconductor-bumphunter
    - r-outliers
    - bioconductor-annotatr
    - bioconductor-annotationhub
    - bioconductor-bsseq
  # these are conda packages that you'll need at runtime
  run:
    - bioconductor-bsseq

# tests that are run after installation
test:
  commands:
    - $R -e "library('dmrseq')"           # [not win]
    - "\"%R%\" -e \"library('dmrseq')\""  # [win]

about:
  home: http://github.com/kdkorthauer/dmrseq
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE

